# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Site specific (non jekyll related).
title: fungai.org - identify wild mushroom with deep learning
purpose: >
  fungai.org assists scientists and enthusiasts to easily identify wild mushroom species from images
  using deep learning technologies.
bio: fungai.org - a wild mushroom ID machine
description: >
  fungai.org assists scientists and enthusiasts to easily identify wild mushroom species from images
  using deep learning technologies.

# Site specific: how many posts to display at home page?
posts_limits: 2

# specific: Credit footer (foot.html) - populate this to form the string at the bottom
client: fungai.org
github_repo_url: https://github.com/Atlas7/fungai-blog

# Deployment specific
#
# Option 1 - use github domain. e.g. https://atlas7.github.io/fungai-blog
#baseurl: "/fungai-blog"
#url: "https://atlas7.github.io"
#
# Option 2 - use custom domain. e.g. http://fungai.org
#url: "/"
url: "http://fungai.org"
baseurl: ""

# Define how individual post URL looks.
# e.g. a post with a name like this: 2016-11-28-placeholder-1.md
# ... will have a URL looke this: http://fungai.org/2016/11/28/placeholder-1
# Note, the following value is equivalent to "pretty"
permalink: /:year/:month/:day/:title/

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true

# This comes with the massively theme. Don't think it is used.
sass:
  sass_dir: _sass
  style: compressed

# Comments (Comment out if not used)
disqus_shortname: "fungai-org"

# Site specific social contacts. Only used in Contact section
# leave blank to hide icon
analytics-id: UA-53715022-4
twitter: jatlas7
#facebook:
#instagram:
githubid: Atlas7
location: Earth
location_url: "https://en.wikipedia.org/wiki/Earth"
CTO:
  name: "Johnny Chan"
  url: "https://twitter.com/jAtlas7"
email: info@fungai.org

# Messages sent via website message box will send to here (via formspree.io)
# Reference: https://formspree.io/
email2: "info@fungai.org"

# Jekyll-paginate - how many blog posts displayed per page (used in blog section)
paginate: 4
paginate_path: "blog/page:num/"

# Comes with Massively Theme. Note quite sure if this is used.
jekyll-mentions:
    base_url: https://github.com

# Exclude list. Comes with Massively Theme.
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]

# Facebook Open Graph (og)
fb_app_id: "592818501079290"