# Site
title: fungai.org - identify wild mushroom with deep learning
purpose: >
  fungai.org assists scientists and enthusiasts to easily identify wild mushroom species from images
  using deep learning technologies.
bio: fungai.org - a wild mushroom ID machine
description: The official homepage of fungai.org

# index.html - how many posts to display at home page?
posts_limits: 10

# Credit footer (foot.html) - populate this to form the string at the bottom
# Further developed by [developer](developer_github) for client
client: fungai.org
github_repo_url: https://github.com/Atlas7/fungai-blog

locale: en_US
baseurl: "/fungai-blog" # the subpath of your site, e.g. /blog
url: "https://atlaas7.github.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   # leave blank to hide icon

# Social
# leave blank to hide icon
#analytics-id:
twitter: jatlas7
#facebook:
#instagram:
githubid: Atlas7

# This is displayed on website footer
location: Earth
location_url: "https://en.wikipedia.org/wiki/Earth"
CTO: Johnny Chan
CTO_url: "https://atlas7.github.io"
#phone1:
#phone2:

# This is displayed on website footer
email: "fungai.org@gmail.com"

# Messages sent via website message box will send to here (via formspree.io)
# Reference: https://formspree.io/
email2: "fungai.org@gmail.com"

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

# Explicitly turn off the old code  (jekyll-paginate)
#paginate: 6
#paginate_path: "/blog/page:num/"
paginate: nil
paginate_path: nil

# Pagination Settings (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 1
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
